from ClaseNinja import Ninja
from ClaseMascota import MascotasVoladoras, MascotasAcuaticas,MascotasTerrestres

ninja1 = Ninja("Sebas","Del Sol")
ninja1.mascotas.append(MascotasVoladoras("Ohub","pez",["ratones","conejos"],10,10,100))
ninja1.mascotas.append(MascotasTerrestres("Acav","vaca","pasto",5,1,100))
ninja1.mascotas.append(MascotasVoladoras("Atoivag","gaviota",["peces","cosas_raritas"],5,1,4))
ninja1.mascotas.append(MascotasVoladoras("Orol","loro",["nueces","semillas"],2,3,80))
ninja1.mascotas.append(MascotasAcuaticas("Zep","pez",["algoraro","insectos"],2.5,0,70))
ninja1.mascotas.append(MascotasVoladoras("Ylf", "mariposa",["frutas podridas","agua"],1,1,10))
print("///////////////////////////////////")
ninja2 = Ninja("Kleo","Dejipto")
ninja2.mascotas.append(MascotasAcuaticas("Oplup","pulpo",["peces","cangrejos"],10,0,85))
print("///////////////////////////////////")
ninja1.actividad("Atoivag",10).actividad("Ylf",1).actividad("Zep").actividad("Acav")
ninja2.actividad("Oplup")
print("///////////////////////////////////")
ninja1.alimentar("Orol").alimentar("Acav").alimentar("Atoivag").cantidad_comida_restante("Orol")
ninja2.alimentar("Oplup")
print("///////////////////////////////////")
ninja1.banar("Atoivag").banar("Orol").banar("Zep")
ninja2.banar("Oplup")
print("///////////////////////////////////")
ninja1.imprimir_datos_por_ninja()
ninja2.imprimir_datos_por_ninja()
print("///////////////////////////////////")
Ninja.imprimir_todos_ninjas()